version: "3"
services:
  postgres_tests:
    image: postgis/postgis:13-3.0
    env_file: postgres.test.env
    command: postgres -c fsync=off
    tmpfs: /pgdata
    restart: on-failure
    ports:
      - 6544:6544
  backend_tests:
    build: backend
    env_file: backend.test.env
    volumes:
      - "./backend:/app"
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -nd pytest src"
    restart: on-failure
    depends_on:
      - postgres_tests
    links:
      - postgres_tests
  media_tests:
    build: media
    env_file: media.test.env
    command: pytest src
    restart: on-failure
