version: "3"
services:
  proxy:
    build: proxy
    restart: on-failure
    ports:
      - 8888:8888
      - 9901:9901
  postgres:
    image: postgis/postgis:13-3.0
    env_file: postgres.dev.env
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    restart: on-failure
    ports:
      - 6545:6545
  postgres_tests:
    image: postgis/postgis:13-3.0
    env_file: postgres.test.env
    command: postgres -c fsync=off
    tmpfs: /pgdata
    restart: on-failure
    ports:
      - 6544:6544
  backend_tests:
    build: backend
    env_file: backend.test.env
    volumes:
      - "./backend:/app"
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -nd pytest src"
    restart: on-failure
    depends_on:
      - postgres_tests
    links:
      - postgres_tests
  backend:
    build: backend
    env_file: backend.dev.env
    volumes:
      - "./backend:/app"
    # see https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -rndz python src/app.py && exit 1"
    restart: on-failure
    ports:
      - 1751:1751
      - 1752:1752
      - 1753:1753
    depends_on:
      - postgres
    links:
      - postgres
  media_tests:
    build: media
    env_file: media.test.env
    command: pytest src
    restart: on-failure
  media:
    build: media
    env_file: media.dev.env
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - backend
    links:
      - backend
#  frontend:
#    build: frontend
#    volumes:
#      - "./frontend:/app"
#    command: sh -c "yarn && yarn start"
#    restart: on-failure
#    ports:
#      - 3000:3000
#    depends_on:
#      - backend
#    links:
#      - backend
  vue:
    build: vue
    volumes:
      - "./vue:/app"
    command: sh -c "yarn && yarn dev"
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - backend
