[tool.black]
line-length = 120

[tool.isort]
skip_gitignore = true
include_trailing_comma = true
multi_line_output = 3
line_length = 120

[tool.coverage.run]
omit = ["src/proto/*", "src/couchers/migrations/*", "src/dummy_data.py"]
