name: Prod - Deploy Frontend on Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:

  build-prod:
    runs-on: [self-hosted, master]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/generate-protos
      - uses: ./.github/actions/build-push-ecr
        with:
          module-name: frontend
          extra-build-args: -f prod.Dockerfile
          image-name: frontend-prod
          src-path: ./

  deploy-prod:
    runs-on: [self-hosted, master]
    needs: build-prod
    environment:
      name: prod
      url: couchers.org
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/helm-deploy
        with:
          environment-slug: prod
          environment-name: prod

  notify-slack:
    runs-on: [self-hosted, master]
    needs: deploy-prod
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Web-Frontend was Deployed to Production",
              "channel": "C01PWQEJ2SY",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Web-Frontend was Deployed to Production"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The web frontend was just deployed to <https://couchers.org|production>.\n*Ref:* ${{github.ref_name}}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
